
spring.datasource.url=jdbc:postgresql://dpg-dathlkegekts73as9990-a.oregon-postgres.render.com:5432/donaciones_6pzo_celm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=donaciones_6pzo_user
spring.datasource.password=XZXYWYPOtDzIRq86B2ijaQk4ZnuEIgJn
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.ar.edu.utn.dds.k3003=INFO



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# datadog
management.datadog.metrics.export.enabled=${DATADOG_ENABLED:false}
management.datadog.metrics.export.api-key=${DATADOG_API_KEY:}
management.datadog.metrics.export.application-key=${DATADOG_APP_KEY:}
management.datadog.metrics.export.step=1m
management.datadog.metrics.export.uri=${DATADOG_URI:https://api.datadoghq.com}/
management.metrics.tags.modulo=donaciones



# Microservicios
INCENTIVOS_SERVICE_URL=https://incentivos-cxk9.onrender.com
LOGISTICA_SERVICE_URL=https://logistica-tk85.onrender.com
DONADORESYENTIDADES_URL=https://donadoresyentidades.onrender.com


server.port=${PORT:8081}