
spring.datasource.url=jdbc:postgresql://dpg-d8j2e448aovs738ru5c0-a.oregon-postgres.render.com:5432/donaciones_gv65
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=donaciones_gv65_user
spring.datasource.password=J5FKiq7Saap7qZudrEgZyDFk5i9m3vh6
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# datadog
management.datadog.metrics.export.uri=https://api.us5.datadoghq.com
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=30s
management.datadog.metrics.export.apikey=5d8de77c6c2a54c43f53025b89e48733
management.datadog.metrics.export.applicationKey=ddapp_D2utasnadDFAlnGE7TEplQ6Y76TC14VtSz
management.metrics.tags.modulo=donaciones

spring.devtools.restart.enabled=true

# Microservicios
INCENTIVOS_SERVICE_URL=https://incentivos-cxk9.onrender.com
LOGISTICA_SERVICE_URL=https://logistica-tk85.onrender.com
DONADORESYENTIDADES_URL=https://donadoresyentidades.onrender.com


server.port=${PORT:8080}